const actionTypes = Object.freeze({
    //user login 
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAIL: 'GET_ACCOUNT_FAIL',

    REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',

    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',


    // books 
    GET_TAGTYPE_REQUEST: 'GET_TAGTYPE_REQUEST',
    GET_TAGTYPE_SUCCESS: 'GET_TAGTYPE_SUCCESS',
    
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS'



})

export default actionTypes;