const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    ADMIN_PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_FAILED : 'FETCH_GENDER_FAILED',
    FETCH_GENDER_SUCCESS : 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_START : 'FETCH_GENDER_START',
    
    FETCH_ROLE_FAILED : 'FETCH_ROLE_FAILED',
    FETCH_ROLE_SUCCESS : 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_START : 'FETCH_ROLE_START',

    FETCH_USER_FAILED : 'FETCH_USER_FAILED',
    FETCH_USER_SUCCESS : 'FETCH_USER_SUCCESS',
    FETCH_USER_START : 'FETCH_USER_START',

    CREATE_USER_START : 'CREATE_USER_START',
    CREATE_USER_SUCCESS : 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED : 'CREATE_USER_FAILED',
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED : 'DELETE_USER_FAILED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',




    // 
})

export default actionTypes;